version: '3.8'

services:
  vuestroapellidobd:  # Renombramos el servicio de base de datos
    image: mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret

volumes:
  data:
