version: '3'

networks:
  ldap_network:
    driver: bridge

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=vuestroapellido,dc=org"
      LDAP_ORGANISATION: "Vuestro Apellido Organization"
      LDAP_DOMAIN: "vuestroapellido.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"             # Desactivar TLS para el servidor LDAP
    networks:
      - ldap_network
    ports:
      - "389:389"                   # Puerto predeterminado para LDAP sin cifrar
    command: --copy-service
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"   # Desactivar HTTPS
    networks:
      - ldap_network
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - openldap
